version: "3.9"

services:
  rybbit_backend:
    image: ghcr.io/rybbit-io/rybbit-backend:latest
    container_name: rybbit_backend
    restart: always
    environment:
      - BASE_URL=https://sensegrid.sltdigitallab.lk/analytics
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - DISABLE_SIGNUP=false
    depends_on:
      - postgres
      - clickhouse
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rybbit-api.rule=Host(`sensegrid.sltdigitallab.lk`) && PathPrefix(`/analytics/api`)"
      - "traefik.http.routers.rybbit-api.entrypoints=websecure"
      - "traefik.http.routers.rybbit-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.rybbit-api.loadbalancer.server.port=3001"
    networks:
      - web

  rybbit_client:
    image: ghcr.io/rybbit-io/rybbit-client:latest
    container_name: rybbit_client
    restart: always
    depends_on:
      - rybbit_backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rybbit-client.rule=Host(`sensegrid.sltdigitallab.lk`) && PathPrefix(`/analytics`)"
      - "traefik.http.routers.rybbit-client.entrypoints=websecure"
      - "traefik.http.routers.rybbit-client.tls.certresolver=letsencrypt"
      - "traefik.http.services.rybbit-client.loadbalancer.server.port=3002"
    networks:
      - web

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: rybbit-clickhouse
    restart: always
    networks:
      - web

  postgres:
    image: postgres:15
    container_name: rybbit-postgres
    restart: always
    environment:
      POSTGRES_USER: rybbit
      POSTGRES_PASSWORD: rybbit
      POSTGRES_DB: analytics
    networks:
      - web

networks:
  web:
    external: true
